# Generated by Django 3.2.2 on 2024-12-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('sum_publish', models.IntegerField(blank=True, null=True)),
                ('sum_download', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('used_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReArticleAuthor',
            fields=[
                ('url_article', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url_author', models.CharField(max_length=255)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 're_article_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReArticleSource',
            fields=[
                ('url_article', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url_source', models.CharField(max_length=255)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 're_article_source',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReAuthorOrganization',
            fields=[
                ('url_author', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 're_author_organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReTeacherStudent',
            fields=[
                ('url_teacher', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url_student', models.CharField(max_length=255)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 're_teacher_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_info', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_info', models.CharField(blank=True, max_length=255, null=True)),
                ('evaluation', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'source',
                'managed': False,
            },
        ),
    ]
